package poem

var poems = []Poem{
	// Tang poetry (唐诗)
	{
		Title:  "静夜思",
		Author: "李白",
		Text:   "床前明月光，疑是地上霜。举头望明月，低头思故乡。",
		Moods:  []string{"nostalgic", "lonely", "calm", "homesick", "melancholy"},
	},
	{
		Title:  "月下独酌·其一",
		Author: "李白",
		Text:   "花间一壶酒，独酌无相亲。举杯邀明月，对影成三人。",
		Moods:  []string{"lonely", "reflective", "melancholy", "calm"},
	},
	{
		Title:  "早发白帝城",
		Author: "李白",
		Text:   "朝辞白帝彩云间，千里江陵一日还。两岸猿声啼不住，轻舟已过万重山。",
		Moods:  []string{"joyful", "hopeful", "energetic", "uplifted"},
	},
	{
		Title:  "黄鹤楼送孟浩然之广陵",
		Author: "李白",
		Text:   "故人西辞黄鹤楼，烟花三月下扬州。孤帆远影碧空尽，唯见长江天际流。",
		Moods:  []string{"nostalgic", "longing", "melancholy", "reflective"},
	},
	{
		Title:  "望岳",
		Author: "杜甫",
		Text:   "岱宗夫如何，齐鲁青未了。造化钟神秀，阴阳割昏晓。荡胸生曾云，决眦入归鸟。会当凌绝顶，一览众山小。",
		Moods:  []string{"inspired", "determined", "awe", "motivated"},
	},
	{
		Title:  "春望",
		Author: "杜甫",
		Text:   "国破山河在，城春草木深。感时花溅泪，恨别鸟惊心。",
		Moods:  []string{"sad", "melancholy", "heartbroken", "anxious"},
	},
	{
		Title:  "登高",
		Author: "杜甫",
		Text:   "无边落木萧萧下，不尽长江滚滚来。万里悲秋常作客，百年多病独登台。",
		Moods:  []string{"melancholy", "sad", "lonely", "reflective"},
	},
	{
		Title:  "闻官军收河南河北",
		Author: "杜甫",
		Text:   "剑外忽传收蓟北，初闻涕泪满衣裳。却看妻子愁何在，漫卷诗书喜欲狂。",
		Moods:  []string{"joyful", "relieved", "hopeful", "grateful"},
	},
	{
		Title:  "春晓",
		Author: "孟浩然",
		Text:   "春眠不觉晓，处处闻啼鸟。夜来风雨声，花落知多少。",
		Moods:  []string{"joy", "calm", "hopeful", "gentle"},
	},
	{
		Title:  "宿建德江",
		Author: "孟浩然",
		Text:   "移舟泊烟渚，日暮客愁新。野旷天低树，江清月近人。",
		Moods:  []string{"melancholy", "lonely", "calm", "reflective"},
	},
	{
		Title:  "送元二使安西",
		Author: "王维",
		Text:   "渭城朝雨浥轻尘，客舍青青柳色新。劝君更尽一杯酒，西出阳关无故人。",
		Moods:  []string{"nostalgic", "longing", "sad", "homesick"},
	},
	{
		Title:  "山居秋暝",
		Author: "王维",
		Text:   "空山新雨后，天气晚来秋。明月松间照，清泉石上流。",
		Moods:  []string{"calm", "tranquil", "peaceful", "serene"},
	},
	{
		Title:  "使至塞上",
		Author: "王维",
		Text:   "大漠孤烟直，长河落日圆。",
		Moods:  []string{"calm", "vast", "reflective", "awe"},
	},
	{
		Title:  "相思",
		Author: "王维",
		Text:   "红豆生南国，春来发几枝。愿君多采撷，此物最相思。",
		Moods:  []string{"nostalgic", "lonely", "love", "romantic", "longing"},
	},
	{
		Title:  "登鹳雀楼",
		Author: "王之涣",
		Text:   "白日依山尽，黄河入海流。欲穷千里目，更上一层楼。",
		Moods:  []string{"hopeful", "inspired", "energetic", "determined"},
	},
	{
		Title:  "凉州词",
		Author: "王之涣",
		Text:   "黄河远上白云间，一片孤城万仞山。羌笛何须怨杨柳，春风不度玉门关。",
		Moods:  []string{"lonely", "melancholy", "heroic", "resilient"},
	},
	{
		Title:  "枫桥夜泊",
		Author: "张继",
		Text:   "月落乌啼霜满天，江枫渔火对愁眠。姑苏城外寒山寺，夜半钟声到客船。",
		Moods:  []string{"melancholy", "lonely", "sad", "homesick"},
	},
	{
		Title:  "江雪",
		Author: "柳宗元",
		Text:   "千山鸟飞绝，万径人踪灭。孤舟蓑笠翁，独钓寒江雪。",
		Moods:  []string{"sad", "lonely", "calm", "stoic", "melancholy"},
	},

	// Song ci (宋词)
	{
		Title:  "水调歌头·明月几时有",
		Author: "苏轼",
		Text:   "明月几时有？把酒问青天。不知天上宫阙，今夕是何年。",
		Moods:  []string{"nostalgic", "reflective", "longing", "melancholy"},
	},
	{
		Title:  "念奴娇·赤壁怀古",
		Author: "苏轼",
		Text:   "大江东去，浪淘尽，千古风流人物。故垒西边，人道是，三国周郎赤壁。",
		Moods:  []string{"inspired", "awe", "heroic", "reflective"},
	},
	{
		Title:  "定风波·莫听穿林打叶声",
		Author: "苏轼",
		Text:   "莫听穿林打叶声，何妨吟啸且徐行。竹杖芒鞋轻胜马，谁怕？一蓑烟雨任平生。",
		Moods:  []string{"resilient", "calm", "determined", "optimistic"},
	},
	{
		Title:  "江城子·乙卯正月二十日夜记梦",
		Author: "苏轼",
		Text:   "十年生死两茫茫，不思量，自难忘。千里孤坟，无处话凄凉。",
		Moods:  []string{"grief", "heartbroken", "melancholy", "longing"},
	},
	{
		Title:  "声声慢·寻寻觅觅",
		Author: "李清照",
		Text:   "寻寻觅觅，冷冷清清，凄凄惨惨戚戚。乍暖还寒时候，最难将息。",
		Moods:  []string{"melancholy", "sad", "anxious", "lonely"},
	},
	{
		Title:  "一剪梅·红藕香残玉簟秋",
		Author: "李清照",
		Text:   "红藕香残玉簟秋。轻解罗裳，独上兰舟。云中谁寄锦书来？雁字回时，月满西楼。",
		Moods:  []string{"longing", "romantic", "melancholy", "nostalgic"},
	},
	{
		Title:  "如梦令·常记溪亭日暮",
		Author: "李清照",
		Text:   "常记溪亭日暮，沉醉不知归路。兴尽晚回舟，误入藕花深处。",
		Moods:  []string{"joyful", "playful", "nostalgic", "lighthearted"},
	},
	{
		Title:  "雨霖铃·寒蝉凄切",
		Author: "柳永",
		Text:   "寒蝉凄切，对长亭晚，骤雨初歇。都门帐饮无绪，留恋处，兰舟催发。",
		Moods:  []string{"sad", "melancholy", "heartbroken", "longing"},
	},
	{
		Title:  "鹊桥仙·纤云弄巧",
		Author: "秦观",
		Text:   "纤云弄巧，飞星传恨，银汉迢迢暗度。金风玉露一相逢，便胜却、人间无数。",
		Moods:  []string{"love", "romantic", "hopeful", "tender"},
	},
	{
		Title:  "青玉案·元夕",
		Author: "辛弃疾",
		Text:   "东风夜放花千树，更吹落、星如雨。宝马雕车香满路，凤箫声动，玉壶光转，一夜鱼龙舞。",
		Moods:  []string{"joyful", "festive", "vivid", "excited"},
	},
	{
		Title:  "破阵子·为陈同甫赋壮词以寄之",
		Author: "辛弃疾",
		Text:   "醉里挑灯看剑，梦回吹角连营。八百里分麾下炙，五十弦翻塞外声。沙场秋点兵。",
		Moods:  []string{"energetic", "heroic", "patriotic", "determined"},
	},
	{
		Title:  "丑奴儿·书博山道中壁",
		Author: "辛弃疾",
		Text:   "少年不识愁滋味，爱上层楼。爱上层楼，为赋新词强说愁。而今识尽愁滋味，欲说还休。欲说还休，却道天凉好个秋。",
		Moods:  []string{"melancholy", "reflective", "wistful", "mature"},
	},
	{
		Title:  "虞美人·春花秋月何时了",
		Author: "李煜",
		Text:   "春花秋月何时了，往事知多少。小楼昨夜又东风，故国不堪回首月明中。",
		Moods:  []string{"melancholy", "nostalgic", "sad", "regretful"},
	},
	{
		Title:  "相见欢·无言独上西楼",
		Author: "李煜",
		Text:   "无言独上西楼，月如钩。寂寞梧桐深院锁清秋。",
		Moods:  []string{"lonely", "melancholy", "sad", "quiet"},
	},
	{
		Title:  "满江红·怒发冲冠",
		Author: "岳飞",
		Text:   "怒发冲冠，凭栏处、潇潇雨歇。抬望眼、仰天长啸，壮怀激烈。",
		Moods:  []string{"angry", "patriotic", "determined", "courageous"},
	},
	{
		Title:  "浣溪沙·一曲新词酒一杯",
		Author: "晏殊",
		Text:   "一曲新词酒一杯，去年天气旧亭台。夕阳西下几时回。",
		Moods:  []string{"nostalgic", "wistful", "reflective", "melancholy"},
	},
}
